manifest:
  remotes:
    # zmk official
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
     # Zephyr
#    - name: zephyrproject-rtos
#      url-base: https://github.com/zephyrproject-rtos
      # bravekarma
    - name: caksoylar
      url-base: https://github.com/caksoylar
      # kyek / duckyb
    - name: duckyb
      url-base: https://github.com/duckyb
      # If you don't use animation delete from Here
      # ulounge
    - name: ulounge
      url-base: https://github.com/ulounge
      # To Here
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v3.7.0
      import: app/west.yml

    - name: urchin-zmk-module
      remote: duckyb
      revision: main

#    - name: zephyr
#      remote: zephyrproject-rtos
#      revision: v3.5-branch
#      import: west.yml

      # If you don't use animation delete from Here
    - name: nice-view-mod
      remote: ulounge
      revision: main
      # To Here
  self:
    path: config
